# Schema for the configuration files of the Registration Type module.
registration_type.settings:
  type: config_object
  label: 'Registration Type settings'
  mapping:
    example:
      type: string
      label: 'Example'
